"""Aggregate internal API routers to avoid FastAPI lifespan nesting issues."""

from fastapi import APIRouter

from app.routers import (
    admin,
    ai,
    ai_chat,
    ai_enhanced,
    audits,
    auth,
    billing,
    care_notes,
    care_plans,
    cqc,
    deterioration,
    developer,
    evidence_packs,
    falls,
    family,
    finance,
    incidents,
    mar,
    onboarding,
    patterns,
    pharmacy,
    reports,
    residents,
    rota,
    safeguarding,
    section42,
    shift_notes,
    staff,
    webhooks,
)
from app.routers.clinical import (
    catheter_stoma,
    eol,
    fluids,
    nutrition,
    vitals,
    wounds,
)

api_router = APIRouter()

for router in (
    auth.router,
    admin.router,
    ai.router,
    ai_chat.router,
    ai_enhanced.router,
    residents.router,
    care_notes.router,
    care_plans.router,
    mar.router,
    incidents.router,
    staff.router,
    rota.router,
    shift_notes.router,
    finance.router,
    billing.router,
    family.router,
    audits.router,
    cqc.router,
    deterioration.router,
    falls.router,
    webhooks.router,
    developer.router,
    reports.router,
    safeguarding.router,
    section42.router,
    patterns.router,
    evidence_packs.router,
    onboarding.router,
    pharmacy.router,
    wounds.router,
    vitals.router,
    fluids.router,
    catheter_stoma.router,
    eol.router,
    nutrition.router,
):
    api_router.include_router(router)
