"""Initial schema with all production models

Revision ID: 001
Revises: 
Create Date: 2026-05-22 15:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Care homes
    op.create_table(
        'care_homes',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('name', sa.String(200), nullable=False),
        sa.Column('registration_number', sa.String(50), nullable=True, unique=True),
        sa.Column('address_line_1', sa.String(255), nullable=False),
        sa.Column('address_line_2', sa.String(255), nullable=True),
        sa.Column('city', sa.String(100), nullable=False),
        sa.Column('postcode', sa.String(20), nullable=False),
        sa.Column('phone', sa.String(50), nullable=False),
        sa.Column('email', sa.String(255), nullable=False),
        sa.Column('nation', sa.String(20), default='england', nullable=False),
        sa.Column('cqc_rating', sa.String(20), nullable=True),
        sa.Column('total_beds', sa.Integer, default=0, nullable=False),
        sa.Column('occupied_beds', sa.Integer, default=0, nullable=False),
        sa.Column('is_nursing_home', sa.Boolean, default=False, nullable=False),
        sa.Column('is_active', sa.Boolean, default=True, nullable=False),
        sa.Column('subscription_tier', sa.String(50), default='free', nullable=False),
        sa.Column('subscription_status', sa.String(50), default='active', nullable=False),
        sa.Column('trial_ends_at', sa.String(50), nullable=True),
        sa.Column('billing_contact', sa.String(255), nullable=True),
        sa.Column('stripe_customer_id', sa.String(100), nullable=True),
        sa.Column('stripe_subscription_id', sa.String(100), nullable=True),
        sa.Column('group_parent_id', sa.String(36), sa.ForeignKey('care_homes.id', ondelete='SET NULL'), nullable=True),
        sa.Column('settings', sa.Text, nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False),
    )

    # Users
    op.create_table(
        'users',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('email', sa.String(255), unique=True, nullable=False, index=True),
        sa.Column('auth0_id', sa.String(255), unique=True, nullable=True),
        sa.Column('first_name', sa.String(100), nullable=False),
        sa.Column('last_name', sa.String(100), nullable=False),
        sa.Column('role', sa.String(50), default='carer', nullable=False),
        sa.Column('is_active', sa.Boolean, default=True, nullable=False),
        sa.Column('is_superuser', sa.Boolean, default=False, nullable=False),
        sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
        sa.Column('care_home_id', sa.String(36), sa.ForeignKey('care_homes.id', ondelete='SET NULL'), nullable=True),
        sa.Column('phone', sa.String(50), nullable=True),
        sa.Column('language_preference', sa.String(10), default='en', nullable=False),
        sa.Column('notification_preferences', sa.Text, nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False),
    )

    # Residents
    op.create_table(
        'residents',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('care_home_id', sa.String(36), sa.ForeignKey('care_homes.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('nhs_number', sa.String(20), nullable=True, index=True),
        sa.Column('gp_practice_code', sa.String(20), nullable=True),
        sa.Column('gp_practice_name', sa.String(200), nullable=True),
        sa.Column('title', sa.String(20), nullable=True),
        sa.Column('first_name', sa.String(100), nullable=False),
        sa.Column('last_name', sa.String(100), nullable=False),
        sa.Column('preferred_name', sa.String(100), nullable=True),
        sa.Column('date_of_birth', sa.Date, nullable=False),
        sa.Column('gender', sa.String(20), nullable=False),
        sa.Column('room', sa.String(50), nullable=False),
        sa.Column('admission_date', sa.Date, nullable=False),
        sa.Column('status', sa.String(20), default='active', nullable=False),
        sa.Column('primary_need', sa.Text, nullable=False),
        sa.Column('secondary_needs', sa.Text, nullable=True),
        sa.Column('mobility', sa.String(50), default='independent', nullable=False),
        sa.Column('falls_risk', sa.String(20), default='medium', nullable=False),
        sa.Column('deterioration_risk', sa.String(20), default='low', nullable=False),
        sa.Column('hydration_status', sa.String(20), default='stable', nullable=False),
        sa.Column('nutrition_status', sa.String(20), default='stable', nullable=False),
        sa.Column('skin_condition', sa.String(100), nullable=True),
        sa.Column('continence_status', sa.String(100), nullable=True),
        sa.Column('communication_needs', sa.Text, nullable=True),
        sa.Column('cognitive_status', sa.String(100), nullable=True),
        sa.Column('dnar_status', sa.Boolean, default=False, nullable=False),
        sa.Column('allergies', sa.Text, nullable=True),
        sa.Column('dietary_requirements', sa.Text, nullable=True),
        sa.Column('weight_kg', sa.Float, nullable=True),
        sa.Column('height_cm', sa.Float, nullable=True),
        sa.Column('bmi', sa.Float, nullable=True),
        sa.Column('family_contact_name', sa.String(200), nullable=True),
        sa.Column('family_contact_phone', sa.String(50), nullable=True),
        sa.Column('family_contact_email', sa.String(255), nullable=True),
        sa.Column('family_contact_relationship', sa.String(50), nullable=True),
        sa.Column('next_of_kin_name', sa.String(200), nullable=True),
        sa.Column('next_of_kin_phone', sa.String(50), nullable=True),
        sa.Column('lpa_health_welfare', sa.Boolean, default=False, nullable=False),
        sa.Column('lpa_property_financial', sa.Boolean, default=False, nullable=False),
        sa.Column('care_plan_review_date', sa.Date, nullable=True),
        sa.Column('last_care_plan_review', sa.DateTime(timezone=True), nullable=True),
        sa.Column('photo_url', sa.String(500), nullable=True),
        sa.Column('notes', sa.Text, nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False),
    )

    # Staff
    op.create_table(
        'staff',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('care_home_id', sa.String(36), sa.ForeignKey('care_homes.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('user_id', sa.String(36), sa.ForeignKey('users.id', ondelete='SET NULL'), nullable=True, unique=True),
        sa.Column('employee_number', sa.String(50), nullable=True, unique=True),
        sa.Column('first_name', sa.String(100), nullable=False),
        sa.Column('last_name', sa.String(100), nullable=False),
        sa.Column('email', sa.String(255), nullable=False),
        sa.Column('phone', sa.String(50), nullable=True),
        sa.Column('role', sa.String(50), nullable=False),
        sa.Column('job_title', sa.String(100), nullable=False),
        sa.Column('department', sa.String(100), nullable=True),
        sa.Column('employment_type', sa.String(50), default='full_time', nullable=False),
        sa.Column('contracted_hours', sa.String(10), default='37.5', nullable=False),
        sa.Column('hourly_rate', sa.String(10), nullable=True),
        sa.Column('annual_salary', sa.String(15), nullable=True),
        sa.Column('start_date', sa.Date, nullable=False),
        sa.Column('end_date', sa.Date, nullable=True),
        sa.Column('is_active', sa.Boolean, default=True, nullable=False),
        sa.Column('dbs_number', sa.String(50), nullable=True),
        sa.Column('dbs_issue_date', sa.Date, nullable=True),
        sa.Column('dbs_expiry_date', sa.Date, nullable=True),
        sa.Column('right_to_work_checked', sa.Boolean, default=False, nullable=False),
        sa.Column('right_to_work_expiry', sa.Date, nullable=True),
        sa.Column('nvq_level', sa.String(50), nullable=True),
        sa.Column('nurse_pin', sa.String(50), nullable=True),
        sa.Column('nurse_pin_expiry', sa.Date, nullable=True),
        sa.Column('training_expiry_dates', sa.Text, nullable=True),
        sa.Column('mandatory_training_status', sa.Text, nullable=True),
        sa.Column('supervisions_due', sa.Date, nullable=True),
        sa.Column('appraisal_due', sa.Date, nullable=True),
        sa.Column('sickness_absences_ytd', sa.Integer, default=0, nullable=False),
        sa.Column('agency_name', sa.String(200), nullable=True),
        sa.Column('is_agency', sa.Boolean, default=False, nullable=False),
        sa.Column('emergency_contact_name', sa.String(200), nullable=True),
        sa.Column('emergency_contact_phone', sa.String(50), nullable=True),
        sa.Column('notes', sa.Text, nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False),
    )

    # Medications
    op.create_table(
        'medications',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('resident_id', sa.String(36), sa.ForeignKey('residents.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('name', sa.String(200), nullable=False),
        sa.Column('generic_name', sa.String(200), nullable=True),
        sa.Column('strength', sa.String(100), nullable=False),
        sa.Column('form', sa.String(50), nullable=False),
        sa.Column('route', sa.String(50), nullable=False),
        sa.Column('frequency', sa.String(100), nullable=False),
        sa.Column('prescribed_dose', sa.String(100), nullable=False),
        sa.Column('max_daily_dose', sa.String(100), nullable=True),
        sa.Column('instructions', sa.Text, nullable=True),
        sa.Column('indications', sa.Text, nullable=True),
        sa.Column('side_effects_to_monitor', sa.Text, nullable=True),
        sa.Column('is_controlled_drug', sa.Boolean, default=False, nullable=False),
        sa.Column('controlled_drug_schedule', sa.String(20), nullable=True),
        sa.Column('is_prn', sa.Boolean, default=False, nullable=False),
        sa.Column('prn_reason', sa.String(200), nullable=True),
        sa.Column('prn_max_daily', sa.Integer, nullable=True),
        sa.Column('is_covert', sa.Boolean, default=False, nullable=False),
        sa.Column('covert_authorisation_date', sa.Date, nullable=True),
        sa.Column('covert_review_date', sa.Date, nullable=True),
        sa.Column('prescribed_by', sa.String(200), nullable=False),
        sa.Column('prescribed_date', sa.Date, nullable=False),
        sa.Column('review_date', sa.Date, nullable=False),
        sa.Column('pharmacy_name', sa.String(200), nullable=True),
        sa.Column('pharmacy_reference', sa.String(100), nullable=True),
        sa.Column('status', sa.String(20), default='active', nullable=False),
        sa.Column('discontinued_date', sa.Date, nullable=True),
        sa.Column('discontinued_reason', sa.String(200), nullable=True),
        sa.Column('ai_interaction_check', sa.Text, nullable=True),
        sa.Column('ai_interaction_date', sa.Date, nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False),
    )

    # Care notes
    op.create_table(
        'care_notes',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('resident_id', sa.String(36), sa.ForeignKey('residents.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('author_id', sa.String(36), sa.ForeignKey('users.id', ondelete='SET NULL'), nullable=False, index=True),
        sa.Column('note_type', sa.String(50), nullable=False),
        sa.Column('content', sa.Text, nullable=False),
        sa.Column('structured_data', sa.Text, nullable=True),
        sa.Column('original_language', sa.String(10), nullable=True),
        sa.Column('original_transcript', sa.Text, nullable=True),
        sa.Column('translation_applied', sa.Boolean, default=False, nullable=False),
        sa.Column('translation_engine', sa.String(50), nullable=True),
        sa.Column('ai_generated', sa.Boolean, default=False, nullable=False),
        sa.Column('ai_model', sa.String(100), nullable=True),
        sa.Column('quality_gate_passed', sa.Boolean, default=True, nullable=False),
        sa.Column('quality_gate_score', sa.String(10), nullable=True),
        sa.Column('cqc_tags', sa.Text, nullable=True),
        sa.Column('safeguarding_flags', sa.Text, nullable=True),
        sa.Column('mood_assessment', sa.String(50), nullable=True),
        sa.Column('pain_score', sa.String(10), nullable=True),
        sa.Column('is_offline_synced', sa.Boolean, default=True, nullable=False),
        sa.Column('offline_job_id', sa.String(50), nullable=True),
        sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False),
    )

    # MAR records
    op.create_table(
        'mar_records',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('resident_id', sa.String(36), sa.ForeignKey('residents.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('medication_id', sa.String(36), sa.ForeignKey('medications.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('administered_by_id', sa.String(36), sa.ForeignKey('users.id', ondelete='SET NULL'), nullable=True),
        sa.Column('scheduled_date', sa.Date, nullable=False, index=True),
        sa.Column('scheduled_time', sa.Time, nullable=False),
        sa.Column('round_name', sa.String(50), nullable=False),
        sa.Column('status', sa.String(50), default='due', nullable=False),
        sa.Column('administered_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('dose_given', sa.String(100), nullable=True),
        sa.Column('route_given', sa.String(50), nullable=True),
        sa.Column('refusal_reason', sa.String(200), nullable=True),
        sa.Column('omission_reason', sa.String(200), nullable=True),
        sa.Column('notes', sa.Text, nullable=True),
        sa.Column('witness_id', sa.String(36), sa.ForeignKey('users.id', ondelete='SET NULL'), nullable=True),
        sa.Column('is_controlled_drug', sa.Boolean, default=False, nullable=False),
        sa.Column('second_checker_id', sa.String(36), sa.ForeignKey('users.id', ondelete='SET NULL'), nullable=True),
        sa.Column('temperature_celsius', sa.String(10), nullable=True),
        sa.Column('batch_number', sa.String(100), nullable=True),
        sa.Column('expiry_date', sa.Date, nullable=True),
        sa.Column('is_offline_synced', sa.Boolean, default=True, nullable=False),
        sa.Column('offline_job_id', sa.String(50), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False),
    )

    # Shifts
    op.create_table(
        'shifts',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('care_home_id', sa.String(36), sa.ForeignKey('care_homes.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('staff_id', sa.String(36), sa.ForeignKey('staff.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('shift_date', sa.Date, nullable=False, index=True),
        sa.Column('shift_type', sa.String(50), nullable=False),
        sa.Column('start_time', sa.Time, nullable=False),
        sa.Column('end_time', sa.Time, nullable=False),
        sa.Column('break_minutes', sa.Integer, default=30, nullable=False),
        sa.Column('status', sa.String(50), default='scheduled', nullable=False),
        sa.Column('role_assigned', sa.String(50), nullable=False),
        sa.Column('department', sa.String(100), nullable=True),
        sa.Column('residents_assigned', sa.Text, nullable=True),
        sa.Column('handover_notes_in', sa.Text, nullable=True),
        sa.Column('handover_notes_out', sa.Text, nullable=True),
        sa.Column('ai_handover_generated', sa.Boolean, default=False, nullable=False),
        sa.Column('ai_handover_content', sa.Text, nullable=True),
        sa.Column('clock_in_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('clock_out_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('clock_in_location', sa.String(200), nullable=True),
        sa.Column('clock_out_location', sa.String(200), nullable=True),
        sa.Column('overtime_minutes', sa.Integer, default=0, nullable=False),
        sa.Column('is_banked', sa.Boolean, default=False, nullable=False),
        sa.Column('is_agency_cover', sa.Boolean, default=False, nullable=False),
        sa.Column('agency_brief_generated', sa.Boolean, default=False, nullable=False),
        sa.Column('agency_brief_content', sa.Text, nullable=True),
        sa.Column('wtd_compliant', sa.Boolean, default=True, nullable=False),
        sa.Column('wtd_hours_week', sa.String(10), nullable=True),
        sa.Column('created_by_id', sa.String(36), sa.ForeignKey('users.id', ondelete='SET NULL'), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False),
    )

    # Incidents
    op.create_table(
        'incidents',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('care_home_id', sa.String(36), sa.ForeignKey('care_homes.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('resident_id', sa.String(36), sa.ForeignKey('residents.id', ondelete='SET NULL'), nullable=True, index=True),
        sa.Column('reported_by_id', sa.String(36), sa.ForeignKey('users.id', ondelete='SET NULL'), nullable=False),
        sa.Column('incident_type', sa.String(100), nullable=False),
        sa.Column('category', sa.String(100), nullable=False),
        sa.Column('severity', sa.String(20), nullable=False),
        sa.Column('status', sa.String(50), default='open', nullable=False),
        sa.Column('title', sa.String(255), nullable=False),
        sa.Column('description', sa.Text, nullable=False),
        sa.Column('immediate_action_taken', sa.Text, nullable=False),
        sa.Column('location', sa.String(200), nullable=True),
        sa.Column('incident_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('resolved_by_id', sa.String(36), sa.ForeignKey('users.id', ondelete='SET NULL'), nullable=True),
        sa.Column('resolution_notes', sa.Text, nullable=True),
        sa.Column('injuries_sustained', sa.Text, nullable=True),
        sa.Column('medical_attention_given', sa.Boolean, default=False, nullable=False),
        sa.Column('medical_attention_details', sa.Text, nullable=True),
        sa.Column('witnesses', sa.Text, nullable=True),
        sa.Column('is_safeguarding', sa.Boolean, default=False, nullable=False),
        sa.Column('safeguarding_category', sa.String(100), nullable=True),
        sa.Column('is_riddor', sa.Boolean, default=False, nullable=False),
        sa.Column('riddor_reported_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('duty_of_candour_triggered', sa.Boolean, default=False, nullable=False),
        sa.Column('duty_of_candour_date', sa.Date, nullable=True),
        sa.Column('family_notified', sa.Boolean, default=False, nullable=False),
        sa.Column('family_notified_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('family_notification_method', sa.String(50), nullable=True),
        sa.Column('gp_notified', sa.Boolean, default=False, nullable=False),
        sa.Column('gp_notified_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('ai_analysis', sa.Text, nullable=True),
        sa.Column('ai_pattern_detected', sa.Boolean, default=False, nullable=False),
        sa.Column('ai_recommendations', sa.Text, nullable=True),
        sa.Column('root_cause_analysis', sa.Text, nullable=True),
        sa.Column('lessons_learned', sa.Text, nullable=True),
        sa.Column('action_items', sa.Text, nullable=True),
        sa.Column('cqc_relevant', sa.Boolean, default=True, nullable=False),
        sa.Column('cqc_quality_statements', sa.Text, nullable=True),
        sa.Column('photos', sa.Text, nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False),
    )

    # Audits
    op.create_table(
        'audits',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('care_home_id', sa.String(36), sa.ForeignKey('care_homes.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('audit_type', sa.String(100), nullable=False),
        sa.Column('template_name', sa.String(200), nullable=True),
        sa.Column('cqc_quality_statement', sa.String(100), nullable=True),
        sa.Column('cqc_regulation', sa.String(50), nullable=True),
        sa.Column('title', sa.String(255), nullable=False),
        sa.Column('status', sa.String(50), default='in_progress', nullable=False),
        sa.Column('scheduled_date', sa.Date, nullable=False),
        sa.Column('completed_date', sa.Date, nullable=True),
        sa.Column('conducted_by', sa.String(200), nullable=False),
        sa.Column('reviewer_id', sa.String(36), sa.ForeignKey('users.id', ondelete='SET NULL'), nullable=True),
        sa.Column('score', sa.Integer, nullable=True),
        sa.Column('max_score', sa.Integer, nullable=True),
        sa.Column('score_percentage', sa.String(10), nullable=True),
        sa.Column('findings', sa.Text, nullable=True),
        sa.Column('actions_required', sa.Text, nullable=True),
        sa.Column('action_deadline', sa.Date, nullable=True),
        sa.Column('improvement_notes', sa.Text, nullable=True),
        sa.Column('evidence_references', sa.Text, nullable=True),
        sa.Column('is_mock_inspection', sa.Boolean, default=False, nullable=False),
        sa.Column('ai_mock_assessment', sa.Text, nullable=True),
        sa.Column('ai_recommendations', sa.Text, nullable=True),
        sa.Column('policy_references', sa.Text, nullable=True),
        sa.Column('staff_interviewed', sa.Text, nullable=True),
        sa.Column('resident_feedback', sa.Text, nullable=True),
        sa.Column('next_audit_due', sa.Date, nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False),
    )

    # Invoices
    op.create_table(
        'invoices',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('care_home_id', sa.String(36), sa.ForeignKey('care_homes.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('invoice_number', sa.String(50), unique=True, nullable=False),
        sa.Column('resident_id', sa.String(36), sa.ForeignKey('residents.id', ondelete='SET NULL'), nullable=True),
        sa.Column('payer_name', sa.String(200), nullable=False),
        sa.Column('payer_type', sa.String(50), nullable=False),
        sa.Column('la_reference', sa.String(100), nullable=True),
        sa.Column('chc_reference', sa.String(100), nullable=True),
        sa.Column('invoice_date', sa.Date, nullable=False),
        sa.Column('due_date', sa.Date, nullable=False),
        sa.Column('period_start', sa.Date, nullable=False),
        sa.Column('period_end', sa.Date, nullable=False),
        sa.Column('weekly_rate', sa.String(15), nullable=False),
        sa.Column('number_of_weeks', sa.String(10), nullable=False),
        sa.Column('subtotal', sa.String(15), nullable=False),
        sa.Column('extras_total', sa.String(15), default='0.00', nullable=False),
        sa.Column('vat_amount', sa.String(15), default='0.00', nullable=False),
        sa.Column('total_amount', sa.String(15), nullable=False),
        sa.Column('amount_paid', sa.String(15), default='0.00', nullable=False),
        sa.Column('balance_due', sa.String(15), nullable=False),
        sa.Column('status', sa.String(50), default='draft', nullable=False),
        sa.Column('payment_method', sa.String(50), nullable=True),
        sa.Column('payment_date', sa.Date, nullable=True),
        sa.Column('sent_at', sa.Date, nullable=True),
        sa.Column('paid_at', sa.Date, nullable=True),
        sa.Column('notes', sa.Text, nullable=True),
        sa.Column('is_la_billing', sa.Boolean, default=False, nullable=False),
        sa.Column('is_chc_billing', sa.Boolean, default=False, nullable=False),
        sa.Column('is_self_funded', sa.Boolean, default=False, nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False),
    )

    # Resident profiles
    op.create_table(
        'resident_profiles',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('resident_id', sa.String(36), sa.ForeignKey('residents.id', ondelete='CASCADE'), nullable=False, unique=True),
        sa.Column('life_history', sa.Text, nullable=True),
        sa.Column('family_background', sa.Text, nullable=True),
        sa.Column('career_history', sa.Text, nullable=True),
        sa.Column('hobbies_interests', sa.Text, nullable=True),
        sa.Column('likes', sa.Text, nullable=True),
        sa.Column('dislikes', sa.Text, nullable=True),
        sa.Column('routines_preferences', sa.Text, nullable=True),
        sa.Column('sleep_pattern', sa.Text, nullable=True),
        sa.Column('bathing_preferences', sa.Text, nullable=True),
        sa.Column('dressing_preferences', sa.Text, nullable=True),
        sa.Column('meal_preferences', sa.Text, nullable=True),
        sa.Column('drink_preferences', sa.Text, nullable=True),
        sa.Column('religious_needs', sa.Text, nullable=True),
        sa.Column('cultural_needs', sa.Text, nullable=True),
        sa.Column('spiritual_needs', sa.Text, nullable=True),
        sa.Column('communication_preferences', sa.Text, nullable=True),
        sa.Column('mobility_aids', sa.Text, nullable=True),
        sa.Column('hearing_aids', sa.Boolean, default=False, nullable=False),
        sa.Column('glasses', sa.Boolean, default=False, nullable=False),
        sa.Column('dentures', sa.Boolean, default=False, nullable=False),
        sa.Column('pressure_cushion', sa.Boolean, default=False, nullable=False),
        sa.Column('call_bell_preference', sa.String(100), nullable=True),
        sa.Column('preferred_staff_gender', sa.String(20), nullable=True),
        sa.Column('photo_urls', sa.Text, nullable=True),
        sa.Column('ai_generated_summary', sa.Text, nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False),
    )

    # Wound assessments
    op.create_table(
        'wound_assessments',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('resident_id', sa.String(36), sa.ForeignKey('residents.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('assessed_by_id', sa.String(36), sa.ForeignKey('users.id', ondelete='SET NULL'), nullable=False),
        sa.Column('assessment_date', sa.Date, nullable=False),
        sa.Column('wound_location', sa.String(200), nullable=False),
        sa.Column('body_map_x', sa.String(10), nullable=True),
        sa.Column('body_map_y', sa.String(10), nullable=True),
        sa.Column('wound_type', sa.String(100), nullable=False),
        sa.Column('wound_cause', sa.String(200), nullable=True),
        sa.Column('length_cm', sa.String(10), nullable=True),
        sa.Column('width_cm', sa.String(10), nullable=True),
        sa.Column('depth_cm', sa.String(10), nullable=True),
        sa.Column('tissue_type', sa.String(100), nullable=True),
        sa.Column('tissue_percentage', sa.String(50), nullable=True),
        sa.Column('exudate_amount', sa.String(50), nullable=True),
        sa.Column('exudate_type', sa.String(100), nullable=True),
        sa.Column('odour', sa.String(50), nullable=True),
        sa.Column('wound_edge', sa.String(100), nullable=True),
        sa.Column('periwound_skin', sa.String(100), nullable=True),
        sa.Column('pain_score', sa.Integer, nullable=True),
        sa.Column('infection_signs', sa.Text, nullable=True),
        sa.Column('healing_status', sa.String(50), default='assessing', nullable=False),
        sa.Column('healing_trajectory', sa.String(50), nullable=True),
        sa.Column('dressing_type', sa.String(200), nullable=True),
        sa.Column('dressing_change_frequency', sa.String(50), nullable=True),
        sa.Column('next_dressing_change', sa.Date, nullable=True),
        sa.Column('photo_urls', sa.Text, nullable=True),
        sa.Column('plan', sa.Text, nullable=True),
        sa.Column('referral_made', sa.Boolean, default=False, nullable=False),
        sa.Column('referral_to', sa.String(200), nullable=True),
        sa.Column('notes', sa.Text, nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False),
    )

    # Vital signs
    op.create_table(
        'vital_signs',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('resident_id', sa.String(36), sa.ForeignKey('residents.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('recorded_by_id', sa.String(36), sa.ForeignKey('users.id', ondelete='SET NULL'), nullable=False),
        sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('systolic_bp', sa.Integer, nullable=True),
        sa.Column('diastolic_bp', sa.Integer, nullable=True),
        sa.Column('pulse_rate', sa.Integer, nullable=True),
        sa.Column('respiration_rate', sa.Integer, nullable=True),
        sa.Column('spo2_percent', sa.Integer, nullable=True),
        sa.Column('spo2_on_o2', sa.Boolean, default=False, nullable=False),
        sa.Column('o2_flow_rate', sa.String(10), nullable=True),
        sa.Column('temperature_celsius', sa.String(10), nullable=True),
        sa.Column('blood_glucose_mmol', sa.String(10), nullable=True),
        sa.Column('consciousness_level', sa.String(20), nullable=True),
        sa.Column('pain_score', sa.Integer, nullable=True),
        sa.Column('weight_kg', sa.String(10), nullable=True),
        sa.Column('news2_score', sa.Integer, nullable=True),
        sa.Column('news2_risk_category', sa.String(50), nullable=True),
        sa.Column('news2_escalation_triggered', sa.Boolean, default=False, nullable=False),
        sa.Column('escalation_action', sa.Text, nullable=True),
        sa.Column('escalation_completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('escalation_completed_by', sa.String(200), nullable=True),
        sa.Column('is_offline_synced', sa.Boolean, default=True, nullable=False),
        sa.Column('notes', sa.Text, nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False),
    )

    # Fluid balance
    op.create_table(
        'fluid_balances',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('resident_id', sa.String(36), sa.ForeignKey('residents.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('recorded_by_id', sa.String(36), sa.ForeignKey('users.id', ondelete='SET NULL'), nullable=False),
        sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('balance_date', sa.Date, nullable=False, index=True),
        sa.Column('entry_type', sa.String(50), nullable=False),
        sa.Column('fluid_type', sa.String(100), nullable=False),
        sa.Column('route', sa.String(50), nullable=False),
        sa.Column('volume_ml', sa.Integer, nullable=False),
        sa.Column('is_intake', sa.Boolean, nullable=False),
        sa.Column('cumulative_intake_ml', sa.Integer, nullable=True),
        sa.Column('cumulative_output_ml', sa.Integer, nullable=True),
        sa.Column('cumulative_balance_ml', sa.Integer, nullable=True),
        sa.Column('target_intake_ml', sa.Integer, nullable=True),
        sa.Column('deviation_from_target_ml', sa.Integer, nullable=True),
        sa.Column('deviation_alert_triggered', sa.Boolean, default=False, nullable=False),
        sa.Column('notes', sa.Text, nullable=True),
        sa.Column('is_offline_synced', sa.Boolean, default=True, nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False),
    )

    # Catheter / stoma records
    op.create_table(
        'catheter_stoma_records',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('resident_id', sa.String(36), sa.ForeignKey('residents.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('recorded_by_id', sa.String(36), sa.ForeignKey('users.id', ondelete='SET NULL'), nullable=False),
        sa.Column('record_type', sa.String(50), nullable=False),
        sa.Column('insertion_date', sa.Date, nullable=False),
        sa.Column('catheter_type', sa.String(100), nullable=True),
        sa.Column('catheter_size', sa.String(20), nullable=True),
        sa.Column('stoma_type', sa.String(100), nullable=True),
        sa.Column('stoma_location', sa.String(200), nullable=True),
        sa.Column('brand', sa.String(100), nullable=True),
        sa.Column('batch_number', sa.String(100), nullable=True),
        sa.Column('change_frequency_days', sa.Integer, nullable=True),
        sa.Column('next_change_due', sa.Date, nullable=True),
        sa.Column('urine_colour', sa.String(50), nullable=True),
        sa.Column('urine_clarity', sa.String(50), nullable=True),
        sa.Column('urine_odour', sa.String(50), nullable=True),
        sa.Column('urine_amount_ml', sa.Integer, nullable=True),
        sa.Column('stoma_output_consistency', sa.String(50), nullable=True),
        sa.Column('stoma_output_amount', sa.String(50), nullable=True),
        sa.Column('peristomal_skin_condition', sa.String(100), nullable=True),
        sa.Column('complications', sa.Text, nullable=True),
        sa.Column('notes', sa.Text, nullable=True),
        sa.Column('is_active', sa.Boolean, default=True, nullable=False),
        sa.Column('removed_date', sa.Date, nullable=True),
        sa.Column('removed_reason', sa.String(200), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False),
    )

    # End of life care
    op.create_table(
        'end_of_life_care',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('resident_id', sa.String(36), sa.ForeignKey('residents.id', ondelete='CASCADE'), nullable=False, unique=True),
        sa.Column('eol_care_plan_active', sa.Boolean, default=False, nullable=False),
        sa.Column('eol_care_plan_date', sa.Date, nullable=True),
        sa.Column('estimated_prognosis', sa.String(200), nullable=True),
        sa.Column('preferred_place_of_death', sa.String(200), nullable=True),
        sa.Column('dnar_in_place', sa.Boolean, default=False, nullable=False),
        sa.Column('dnar_date', sa.Date, nullable=True),
        sa.Column('dnar_discussed_with_resident', sa.Boolean, default=False, nullable=False),
        sa.Column('dnar_discussed_with_family', sa.Boolean, default=False, nullable=False),
        sa.Column('dnar_discussed_with_gp', sa.Boolean, default=False, nullable=False),
        sa.Column('dnar_document_url', sa.String(500), nullable=True),
        sa.Column('advance_decision_to_refuse_treatment', sa.Boolean, default=False, nullable=False),
        sa.Column('adrt_date', sa.Date, nullable=True),
        sa.Column('adrt_document_url', sa.String(500), nullable=True),
        sa.Column('lpa_health_welfare_name', sa.String(200), nullable=True),
        sa.Column('lpa_health_welfare_phone', sa.String(50), nullable=True),
        sa.Column('coordinate_my_care_registered', sa.Boolean, default=False, nullable=False),
        sa.Column('cmc_plan_url', sa.String(500), nullable=True),
        sa.Column('anticipatory_prescribing_in_place', sa.Boolean, default=False, nullable=False),
        sa.Column('just_in_case_medications', sa.Text, nullable=True),
        sa.Column('symptom_management_plan', sa.Text, nullable=True),
        sa.Column('spiritual_support_needs', sa.Text, nullable=True),
        sa.Column('family_support_plan', sa.Text, nullable=True),
        sa.Column('bereavement_support_offered', sa.Boolean, default=False, nullable=False),
        sa.Column('gp_visits_frequency', sa.String(100), nullable=True),
        sa.Column('district_nurse_involved', sa.Boolean, default=False, nullable=False),
        sa.Column('specialist_palliative_care_involved', sa.Boolean, default=False, nullable=False),
        sa.Column('chaplaincy_involved', sa.Boolean, default=False, nullable=False),
        sa.Column('notes', sa.Text, nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False),
    )

    # Nutrition screenings
    op.create_table(
        'nutrition_screenings',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('resident_id', sa.String(36), sa.ForeignKey('residents.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('assessed_by_id', sa.String(36), sa.ForeignKey('users.id', ondelete='SET NULL'), nullable=False),
        sa.Column('assessment_date', sa.Date, nullable=False),
        sa.Column('bmi', sa.String(10), nullable=True),
        sa.Column('weight_kg', sa.String(10), nullable=True),
        sa.Column('height_cm', sa.String(10), nullable=True),
        sa.Column('unplanned_weight_loss_kg', sa.String(10), nullable=True),
        sa.Column('unplanned_weight_loss_percent', sa.String(10), nullable=True),
        sa.Column('weight_loss_time_months', sa.Integer, nullable=True),
        sa.Column('acute_disease_effect', sa.Boolean, default=False, nullable=False),
        sa.Column('must_score', sa.Integer, nullable=True),
        sa.Column('must_risk_category', sa.String(50), nullable=True),
        sa.Column('malnutrition_risk', sa.Boolean, default=False, nullable=False),
        sa.Column('recommended_actions', sa.Text, nullable=True),
        sa.Column('dietitian_referral_made', sa.Boolean, default=False, nullable=False),
        sa.Column('dietitian_referral_date', sa.Date, nullable=True),
        sa.Column('supplement_prescribed', sa.Boolean, default=False, nullable=False),
        sa.Column('supplement_details', sa.Text, nullable=True),
        sa.Column('food_first_approach', sa.Boolean, default=False, nullable=False),
        sa.Column('texture_modification', sa.String(100), nullable=True),
        sa.Column('fluid_target_ml', sa.Integer, nullable=True),
        sa.Column('next_review_date', sa.Date, nullable=True),
        sa.Column('notes', sa.Text, nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False),
    )

    # API keys
    op.create_table(
        'api_keys',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('care_home_id', sa.String(36), sa.ForeignKey('care_homes.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('user_id', sa.String(36), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False),
        sa.Column('name', sa.String(100), nullable=False),
        sa.Column('key_prefix', sa.String(10), nullable=False),
        sa.Column('key_hash', sa.String(255), nullable=False),
        sa.Column('scopes', sa.Text, nullable=False),
        sa.Column('rate_limit_per_hour', sa.Integer, default=1000, nullable=False),
        sa.Column('requests_count_24h', sa.Integer, default=0, nullable=False),
        sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('is_active', sa.Boolean, default=True, nullable=False),
        sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('revoked_reason', sa.String(200), nullable=True),
        sa.Column('ip_whitelist', sa.Text, nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False),
    )

    # Webhook subscriptions
    op.create_table(
        'webhook_subscriptions',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('care_home_id', sa.String(36), sa.ForeignKey('care_homes.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('name', sa.String(100), nullable=False),
        sa.Column('url', sa.String(500), nullable=False),
        sa.Column('secret', sa.String(255), nullable=True),
        sa.Column('events', sa.Text, nullable=False),
        sa.Column('is_active', sa.Boolean, default=True, nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('last_delivered_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('delivery_count', sa.Integer, default=0, nullable=False),
        sa.Column('failure_count', sa.Integer, default=0, nullable=False),
        sa.Column('headers', sa.Text, nullable=True),
        sa.Column('retry_policy', sa.String(50), default='exponential', nullable=False),
        sa.Column('max_retries', sa.Integer, default=5, nullable=False),
    )

    # Webhook deliveries
    op.create_table(
        'webhook_deliveries',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('subscription_id', sa.String(36), sa.ForeignKey('webhook_subscriptions.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('event_type', sa.String(100), nullable=False),
        sa.Column('payload', sa.Text, nullable=False),
        sa.Column('status', sa.String(50), default='pending', nullable=False),
        sa.Column('http_status_code', sa.Integer, nullable=True),
        sa.Column('response_body', sa.Text, nullable=True),
        sa.Column('attempt_count', sa.Integer, default=0, nullable=False),
        sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('error_message', sa.Text, nullable=True),
        sa.Column('duration_ms', sa.Integer, nullable=True),
        sa.Column('signature', sa.String(255), nullable=True),
    )

    # Pharmacy integrations
    op.create_table(
        'pharmacy_integrations',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('care_home_id', sa.String(36), sa.ForeignKey('care_homes.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('pharmacy_name', sa.String(200), nullable=False),
        sa.Column('integration_type', sa.String(50), nullable=False),
        sa.Column('status', sa.String(50), default='pending', nullable=False),
        sa.Column('api_endpoint', sa.String(500), nullable=True),
        sa.Column('api_key_encrypted', sa.String(500), nullable=True),
        sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_sync_status', sa.String(50), nullable=True),
        sa.Column('last_sync_error', sa.Text, nullable=True),
        sa.Column('auto_sync_enabled', sa.Boolean, default=False, nullable=False),
        sa.Column('sync_frequency_minutes', sa.String(10), default='60', nullable=False),
        sa.Column('medications_synced_count', sa.String(10), default='0', nullable=False),
        sa.Column('prescription_alerts_enabled', sa.Boolean, default=True, nullable=False),
        sa.Column('blister_pack_reconciliation_enabled', sa.Boolean, default=False, nullable=False),
        sa.Column('configuration', sa.Text, nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False),
    )

    # Onboarding progress
    op.create_table(
        'onboarding_progress',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('care_home_id', sa.String(36), sa.ForeignKey('care_homes.id', ondelete='CASCADE'), nullable=False, unique=True),
        sa.Column('user_id', sa.String(36), sa.ForeignKey('users.id', ondelete='SET NULL'), nullable=True),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('phase', sa.String(50), default='setup', nullable=False),
        sa.Column('day_30_completed', sa.Boolean, default=False, nullable=False),
        sa.Column('day_60_completed', sa.Boolean, default=False, nullable=False),
        sa.Column('day_90_completed', sa.Boolean, default=False, nullable=False),
        sa.Column('day_30_completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('day_60_completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('day_90_completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('home_details_configured', sa.Boolean, default=False, nullable=False),
        sa.Column('residents_imported', sa.Boolean, default=False, nullable=False),
        sa.Column('staff_setup_complete', sa.Boolean, default=False, nullable=False),
        sa.Column('care_plan_templates_loaded', sa.Boolean, default=False, nullable=False),
        sa.Column('mar_configured', sa.Boolean, default=False, nullable=False),
        sa.Column('first_care_note_recorded', sa.Boolean, default=False, nullable=False),
        sa.Column('first_incident_recorded', sa.Boolean, default=False, nullable=False),
        sa.Column('cqc_evidence_linked', sa.Boolean, default=False, nullable=False),
        sa.Column('training_completed', sa.Boolean, default=False, nullable=False),
        sa.Column('go_live_checklist_complete', sa.Boolean, default=False, nullable=False),
        sa.Column('go_live_date', sa.Date, nullable=True),
        sa.Column('data_migration_source', sa.String(100), nullable=True),
        sa.Column('data_migration_status', sa.String(50), nullable=True),
        sa.Column('champion_identified', sa.Boolean, default=False, nullable=False),
        sa.Column('champion_name', sa.String(200), nullable=True),
        sa.Column('champion_email', sa.String(255), nullable=True),
        sa.Column('success_call_7_day_completed', sa.Boolean, default=False, nullable=False),
        sa.Column('success_call_30_day_completed', sa.Boolean, default=False, nullable=False),
        sa.Column('success_call_90_day_completed', sa.Boolean, default=False, nullable=False),
        sa.Column('notes', sa.Text, nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False),
    )

    # Training modules
    op.create_table(
        'training_modules',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('care_home_id', sa.String(36), sa.ForeignKey('care_homes.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('title', sa.String(255), nullable=False),
        sa.Column('description', sa.Text, nullable=True),
        sa.Column('target_roles', sa.Text, nullable=False),
        sa.Column('content_url', sa.String(500), nullable=True),
        sa.Column('video_url', sa.String(500), nullable=True),
        sa.Column('duration_minutes', sa.Integer, nullable=True),
        sa.Column('is_mandatory', sa.Boolean, default=False, nullable=False),
        sa.Column('is_onboarding', sa.Boolean, default=False, nullable=False),
        sa.Column('completion_required', sa.Boolean, default=True, nullable=False),
        sa.Column('order_index', sa.Integer, default=0, nullable=False),
        sa.Column('is_active', sa.Boolean, default=True, nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False),
    )

    # Migration jobs
    op.create_table(
        'migration_jobs',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('care_home_id', sa.String(36), sa.ForeignKey('care_homes.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('source_system', sa.String(100), nullable=False),
        sa.Column('migration_type', sa.String(100), nullable=False),
        sa.Column('status', sa.String(50), default='pending', nullable=False),
        sa.Column('file_name', sa.String(255), nullable=True),
        sa.Column('file_url', sa.String(500), nullable=True),
        sa.Column('total_records', sa.Integer, nullable=True),
        sa.Column('processed_records', sa.Integer, default=0, nullable=False),
        sa.Column('success_count', sa.Integer, default=0, nullable=False),
        sa.Column('error_count', sa.Integer, default=0, nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('error_log', sa.Text, nullable=True),
        sa.Column('field_mapping', sa.Text, nullable=True),
        sa.Column('created_by_id', sa.String(36), sa.ForeignKey('users.id', ondelete='SET NULL'), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False),
    )

    # Indexes
    op.create_index('idx_residents_care_home', 'residents', ['care_home_id'])
    op.create_index('idx_residents_name', 'residents', ['first_name', 'last_name'])
    op.create_index('idx_care_notes_resident_date', 'care_notes', ['resident_id', 'recorded_at'])
    op.create_index('idx_mar_records_date', 'mar_records', ['scheduled_date'])
    op.create_index('idx_shifts_date', 'shifts', ['shift_date'])
    op.create_index('idx_incidents_date', 'incidents', ['incident_date'])
    op.create_index('idx_vital_signs_resident_date', 'vital_signs', ['resident_id', 'recorded_at'])
    op.create_index('idx_fluid_balance_date', 'fluid_balances', ['resident_id', 'balance_date'])


def downgrade() -> None:
    op.drop_table('migration_jobs')
    op.drop_table('training_modules')
    op.drop_table('onboarding_progress')
    op.drop_table('pharmacy_integrations')
    op.drop_table('webhook_deliveries')
    op.drop_table('webhook_subscriptions')
    op.drop_table('api_keys')
    op.drop_table('nutrition_screenings')
    op.drop_table('end_of_life_care')
    op.drop_table('catheter_stoma_records')
    op.drop_table('fluid_balances')
    op.drop_table('vital_signs')
    op.drop_table('wound_assessments')
    op.drop_table('resident_profiles')
    op.drop_table('invoices')
    op.drop_table('audits')
    op.drop_table('incidents')
    op.drop_table('shifts')
    op.drop_table('mar_records')
    op.drop_table('care_notes')
    op.drop_table('medications')
    op.drop_table('staff')
    op.drop_table('residents')
    op.drop_table('users')
    op.drop_table('care_homes')
